### ISSUE TITLE
First time Deployment ; "database"

### ISSUE THREAD

**Issue by circuitsunfish** [bromeliad-studios/plant-watering-app#17]
l o l 
where ever will we store the data

**Comment by circuitsunfish** [comment]
https://stackoverflow.com/questions/41114866/how-to-use-firebase-with-ruby-on-rails

**Comment by circuitsunfish** [comment]
according to this video, no ActiveRecord support https://www.youtube.com/watch?v=x73-uoXboPQ

**Comment by circuitsunfish** [comment]
Could set up a rails docker image on Back4app https://www.back4app.com/docs-containers/how-to-create-a-dockerfile

**Comment by circuitsunfish** [comment]
https://fly.io/docs/languages-and-frameworks/ruby/ explicit ruby support on this vendor

**Comment by circuitsunfish** [comment]
Fly appears to be v easy to set up. https://fly.io/docs/postgres/getting-started/what-you-should-know/

**Comment by circuitsunfish** [comment]
an issue with fly when attempting 1st time setup is that a gem could not compile (pg client.)

Provided apt install libpq-dev per advice from error message, see log file in fly console

```
24  bundle install
   25  less /var/lib/gems/2.7.0/extensions/x86_64-linux/2.7.0/pg-1.4.5/mkmf.log
   26  which apt
   27  apt install libpq-dev
```

**Comment by circuitsunfish** [comment]
There also appears to be some unexpected behavior (I suspect) with Fly's unconventional usage of Dockerfiles to deploy vms. for more https://fly.io/ruby-dispatch/rails-on-docker/

`Error failed to fetch an image or build from source: error building: failed to solve with frontend dockerfile.v0: failed to create LLB definition: the Dockerfile cannot be empty`

```
/var/lib/gems/2.7.0/gems/dockerfile-rails-1.0.14/lib/generators/dockerfile_generator.rb:480:in `block in api_client_dir': undefined method `load_file' for JSON:Module (NoMethodError) Error Failed to generate Dockefile: exit status 1
```

**Comment by circuitsunfish** [comment]
moving to `flyctl` from workstation command line gets similar error message with what appears to be the builtin version of ruby on mac

```
/Users/ashton/.rvm/gems/ruby-2.7.4/gems/dockerfile-rails-1.0.14/lib/generators/dockerfile_generator.rb:480:in `block in api_client_dir': undefined method `load_file' for JSON:Module (NoMethodError)
Error Failed to generate Dockefile: exit status 1


```

**Comment by circuitsunfish** [comment]
these are all symptoms of failing to run `bundle install` before trying to deploy an app.

**Comment by circuitsunfish** [comment]
options for including operating system dependencies (postgres client, redis) are detailed in the Ruby dockerfile readme here: https://github.com/rubys/dockerfile-rails#overview

**Comment by circuitsunfish** [comment]
app was deployed an hour ago. Needs testing to see if db connection works as we expect then this can be closed

**Comment by circuitsunfish** [comment]
working on documentation

**Comment by circuitsunfish** [comment]
https://ashtonmackenzie.com/2023/02/14/deploying-a-react-ruby-app-on-fly-io-if-youve-never-deployed-a-thing-in-your-life/ documentation is drafted, awaiting feedback / testing.
